services:
  # backend
  backend:
    image: tan254/vehicle_dashboard:backend-latest
    container_name: vehicle_dashboard_service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/vehicle_dashboard
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password123
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_LIQUIBASE_DEFAULTSCHEMA: vehicle_dashboard
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: vehicle_dashboard
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 10

  # nginx and frontend
  nginx:
    image: tan254/vehicle_dashboard:nginx-latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vehicle_dashboard_nginx
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy