services:
  # database
  db:
    image: postgres:16-alpine
    container_name: vehicle_dashboard_db
    environment:
      POSTGRES_DB: vehicle_dashboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d task_manager" ]
      interval: 5s
      timeout: 5s
      retries: 10

  # database gui
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password123
    ports:
      - "5050:80"
    depends_on:
      - db

  # backend
  backend:
    build: ./backend
    container_name: vehicle_dashboard_service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/task_manager
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password123
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
