spring.application.name=backend
server.port=8080
# liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
# docker health check
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always